name: close_ai
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.3.0'

dependencies:
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.30
  auto_route: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  dio: ^5.4.1
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  upgrader: ^10.3.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animation/
